name: versions
on:
  workflow_dispatch: 
  push:

jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up Maven Central Repository
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            server-id: ossrh
            server-username: MAVEN_USERNAME
            server-password: MAVEN_PASSWORD
            gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
            gpg-passphrase: MAVEN_GPG_PASSPHRASE

        - name: Configure Git
          run: |
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git config user.name "${{ github.actor }}"
            git checkout -b new-release

        - name: Publish package
          run: mvn versions:set -DnewVersion=1.0.1 -DprocessAllModules versions:commit
            
        - name: Commit next version
          run: |
            git add .
            git commit -m "update versions"
            git push -u origin new-release

        - name: Create pull request
          uses: repo-sync/pull-request@v2
          with:
            destination_branch: ${{ steps.branch-name.outputs.current_branch }}
            source_branch: new-release
            pr_title: "Release"
            github_token: ${{ secrets.GITHUB_TOKEN }}
            pr_assignee: ${{ github.actor }}

        - name: Publish package
          run: mvn --batch-mode -f pom.xml verify
